// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

import '../../domain/model/user.dart';


// required: associates our `main.dart` with the code generated by Freezed
part 'user.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user.g.dart';

@freezed
class UserState with _$UserState {
  const factory UserState.notLoggedIn() = _UserStateLoading;
  const factory UserState.loggedIn(User user) = _UserStateData;
  const factory UserState.error({String? message}) = _UserStateError;

  factory UserState.fromJson(Map<String, Object?> json) =>
      _$UserStateFromJson(json);
}
